// Generated by tools/fonts/lab.py; do not edit by hand.
use graticule::Face;
use graticule::face::Metrics;
use iced::font::{Font, Weight};

use super::Candidate;

/// The candidate fonts, as their files.
pub const FONTS: &[&[u8]] = &[
    include_bytes!("../../assets/fonts/lab/departure-bold.ttf"),
    include_bytes!("../../assets/fonts/lab/pixel-code.ttf"),
    include_bytes!("../../assets/fonts/lab/fixed-5x7.ttf"),
    include_bytes!("../../assets/fonts/lab/fixed-6x10.ttf"),
    include_bytes!("../../assets/fonts/lab/terminus-12.ttf"),
    include_bytes!("../../assets/fonts/lab/terminus-12-bold.ttf"),
    include_bytes!("../../assets/fonts/lab/greybeard-11.ttf"),
    include_bytes!("../../assets/fonts/lab/greybeard-11-bold.ttf"),
    include_bytes!("../../assets/fonts/lab/scientifica.ttf"),
    include_bytes!("../../assets/fonts/lab/spleen-5x8.ttf"),
    include_bytes!("../../assets/fonts/lab/spleen-6x12.otf"),
    include_bytes!("../../assets/fonts/lab/cozette.ttf"),
    include_bytes!("../../assets/fonts/lab/gohu-11.ttf"),
    include_bytes!("../../assets/fonts/lab/portfolio-6x8.ttf"),
    include_bytes!("../../assets/fonts/lab/hp100lx-6x8.ttf"),
    include_bytes!("../../assets/fonts/lab/unscii-8.ttf"),
];

/// The candidates, measured.
pub const CANDIDATES: &[Candidate] = &[
    Candidate {
        name: "DEPARTURE BOLD",
        licence: "OFL-1.1",
        note: "Departure Mono thickened a pixel to the right.",
        face: Face::new(
            Font {
                weight: Weight::Bold,
                ..Font::new("Departure Mono")
            },
            Metrics {
                em: 11,
                ascent: 11,
                descent: 3,
                advance: 7,
                cap: 8,
                x_height: 6,
                depth: 2,
                left: 1,
                right: 0,
            },
            1,
            12,
        ),
    },
    Candidate {
        name: "PIXEL CODE",
        licence: "OFL-1.1",
        note: "The nearest relative of Departure at a smaller size.",
        face: Face::new(
            Font {
                weight: Weight::Normal,
                ..Font::new("Pixel Code")
            },
            Metrics {
                em: 9,
                ascent: 10,
                descent: 2,
                advance: 6,
                cap: 7,
                x_height: 5,
                depth: 1,
                left: 0,
                right: 1,
            },
            1,
            10,
        ),
    },
    Candidate {
        name: "FIXED 5×7",
        licence: "Public domain",
        note: "X11 misc-fixed: the workstation's smallest face.",
        face: Face::new(
            Font {
                weight: Weight::Normal,
                ..Font::new("Fixed 5x7")
            },
            Metrics {
                em: 7,
                ascent: 6,
                descent: 1,
                advance: 5,
                cap: 6,
                x_height: 4,
                depth: 1,
                left: 0,
                right: 1,
            },
            1,
            7,
        ),
    },
    Candidate {
        name: "FIXED 6×10",
        licence: "Public domain",
        note: "X11 misc-fixed at a small body size.",
        face: Face::new(
            Font {
                weight: Weight::Normal,
                ..Font::new("Fixed 6x10")
            },
            Metrics {
                em: 10,
                ascent: 8,
                descent: 2,
                advance: 6,
                cap: 7,
                x_height: 5,
                depth: 2,
                left: 0,
                right: 1,
            },
            1,
            10,
        ),
    },
    Candidate {
        name: "TERMINUS 12",
        licence: "OFL-1.1",
        note: "Departure's capitals and x-height in a 6 px cell.",
        face: Face::new(
            Font {
                weight: Weight::Normal,
                ..Font::new("Terminus 12")
            },
            Metrics {
                em: 12,
                ascent: 10,
                descent: 2,
                advance: 6,
                cap: 8,
                x_height: 6,
                depth: 2,
                left: 0,
                right: 1,
            },
            1,
            12,
        ),
    },
    Candidate {
        name: "TERMINUS 12 BOLD",
        licence: "OFL-1.1",
        note: "A true bold at body size.",
        face: Face::new(
            Font {
                weight: Weight::Bold,
                ..Font::new("Terminus 12")
            },
            Metrics {
                em: 12,
                ascent: 10,
                descent: 2,
                advance: 6,
                cap: 8,
                x_height: 6,
                depth: 2,
                left: 0,
                right: 1,
            },
            1,
            12,
        ),
    },
    Candidate {
        name: "GREYBEARD 11",
        licence: "MIT",
        note: "A neutral terminal face with a bold at every size.",
        face: Face::new(
            Font {
                weight: Weight::Normal,
                ..Font::new("Greybeard 11px")
            },
            Metrics {
                em: 11,
                ascent: 9,
                descent: 2,
                advance: 6,
                cap: 8,
                x_height: 6,
                depth: 2,
                left: 1,
                right: 1,
            },
            1,
            11,
        ),
    },
    Candidate {
        name: "GREYBEARD 11 BOLD",
        licence: "MIT",
        note: "Greybeard's bold.",
        face: Face::new(
            Font {
                weight: Weight::Bold,
                ..Font::new("Greybeard 11px")
            },
            Metrics {
                em: 11,
                ascent: 9,
                descent: 2,
                advance: 6,
                cap: 8,
                x_height: 6,
                depth: 2,
                left: 0,
                right: 1,
            },
            1,
            11,
        ),
    },
    Candidate {
        name: "SCIENTIFICA",
        licence: "OFL-1.1",
        note: "Condensed: five pixels a cell.",
        face: Face::new(
            Font {
                weight: Weight::Normal,
                ..Font::new("scientifica")
            },
            Metrics {
                em: 11,
                ascent: 9,
                descent: 2,
                advance: 5,
                cap: 7,
                x_height: 5,
                depth: 2,
                left: 0,
                right: 1,
            },
            1,
            11,
        ),
    },
    Candidate {
        name: "SPLEEN 5×8",
        licence: "BSD-2-Clause",
        note: "Squared letterforms, the Portfolio's line.",
        face: Face::new(
            Font {
                weight: Weight::Normal,
                ..Font::new("Spleen 5x8")
            },
            Metrics {
                em: 8,
                ascent: 7,
                descent: 1,
                advance: 5,
                cap: 6,
                x_height: 5,
                depth: 1,
                left: 0,
                right: 1,
            },
            1,
            8,
        ),
    },
    Candidate {
        name: "SPLEEN 6×12",
        licence: "BSD-2-Clause",
        note: "Spleen at body size.",
        face: Face::new(
            Font {
                weight: Weight::Normal,
                ..Font::new("Spleen 6x12")
            },
            Metrics {
                em: 12,
                ascent: 9,
                descent: 3,
                advance: 6,
                cap: 8,
                x_height: 6,
                depth: 3,
                left: 0,
                right: 1,
            },
            1,
            12,
        ),
    },
    Candidate {
        name: "COZETTE",
        licence: "MIT",
        note: "A rounded 6×13 with wide coverage.",
        face: Face::new(
            Font {
                weight: Weight::Normal,
                ..Font::new("CozetteVector")
            },
            Metrics {
                em: 13,
                ascent: 10,
                descent: 3,
                advance: 6,
                cap: 8,
                x_height: 6,
                depth: 3,
                left: 1,
                right: 0,
            },
            1,
            13,
        ),
    },
    Candidate {
        name: "GOHU 11",
        licence: "WTFPL",
        note: "A compact terminal face.",
        face: Face::new(
            Font {
                weight: Weight::Normal,
                ..Font::new("GohuFont 11")
            },
            Metrics {
                em: 11,
                ascent: 9,
                descent: 2,
                advance: 6,
                cap: 8,
                x_height: 5,
                depth: 2,
                left: 0,
                right: 1,
            },
            1,
            11,
        ),
    },
    Candidate {
        name: "PORTFOLIO 6×8",
        licence: "CC BY-SA 4.0",
        note: "A plain 6×8 face from the Oldschool PC Font Pack.",
        face: Face::new(
            Font {
                weight: Weight::Normal,
                ..Font::new("Px437 Portfolio 6x8")
            },
            Metrics {
                em: 8,
                ascent: 7,
                descent: 1,
                advance: 6,
                cap: 7,
                x_height: 5,
                depth: 0,
                left: 0,
                right: 1,
            },
            1,
            8,
        ),
    },
    Candidate {
        name: "HP 100LX 6×8",
        licence: "CC BY-SA 4.0",
        note: "Portfolio's sibling, with descenders.",
        face: Face::new(
            Font {
                weight: Weight::Normal,
                ..Font::new("PxPlus HP 100LX 6x8")
            },
            Metrics {
                em: 8,
                ascent: 7,
                descent: 1,
                advance: 6,
                cap: 7,
                x_height: 5,
                depth: 1,
                left: 1,
                right: 0,
            },
            1,
            8,
        ),
    },
    Candidate {
        name: "UNSCII 8",
        licence: "Public domain",
        note: "Home-computer 8×8 with two-pixel stems.",
        face: Face::new(
            Font {
                weight: Weight::Normal,
                ..Font::new("unscii")
            },
            Metrics {
                em: 8,
                ascent: 8,
                descent: 0,
                advance: 8,
                cap: 8,
                x_height: 6,
                depth: 0,
                left: 1,
                right: 1,
            },
            1,
            8,
        ),
    },
];
